"""
Technical Documentation Service
Generates comprehensive technical documentation for CloudMind components
"""

import logging
from datetime import datetime
from typing import Dict, Any, List, Optional
from pathlib import Path
import json
import yaml

from app.models.user import User, UserRole
from app.schemas.user import UserResponse

logger = logging.getLogger(__name__)


class DocumentationService:
    """Service for generating technical documentation"""
    
    def __init__(self):
        self.docs_path = Path("docs/technical")
        self.docs_path.mkdir(parents=True, exist_ok=True)
    
    async def generate_component_documentation(
        self, 
        component_name: str, 
        component_data: Dict[str, Any],
        doc_type: str = "markdown"
    ) -> str:
        """Generate documentation for a specific component"""
        
        if doc_type == "markdown":
            return await self._generate_markdown_doc(component_name, component_data)
        elif doc_type == "json":
            return await self._generate_json_doc(component_name, component_data)
        elif doc_type == "yaml":
            return await self._generate_yaml_doc(component_name, component_data)
        else:
            raise ValueError(f"Unsupported documentation type: {doc_type}")
    
    async def _generate_markdown_doc(self, component_name: str, component_data: Dict[str, Any]) -> str:
        """Generate markdown documentation"""
        
        doc = f"""# {component_name.replace('_', ' ').title()} Documentation

## Overview
This document provides comprehensive technical documentation for the {component_name} component.

## Component Details

### Basic Information
- **Component Name**: {component_name}
- **Documentation Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Version**: {component_data.get('version', '1.0.0')}

### Architecture
{self._format_architecture_section(component_data)}

### API Endpoints
{self._format_api_endpoints(component_data)}

### Database Schema
{self._format_database_schema(component_data)}

### Security Considerations
{self._format_security_section(component_data)}

### Configuration
{self._format_configuration_section(component_data)}

### Usage Examples
{self._format_usage_examples(component_data)}

### Error Handling
{self._format_error_handling(component_data)}

### Performance Considerations
{self._format_performance_section(component_data)}

### Testing
{self._format_testing_section(component_data)}

### Deployment
{self._format_deployment_section(component_data)}

## Technical Specifications

### Dependencies
{self._format_dependencies(component_data)}

### Environment Variables
{self._format_environment_variables(component_data)}

### Logging
{self._format_logging_section(component_data)}

### Monitoring
{self._format_monitoring_section(component_data)}

## Maintenance

### Troubleshooting
{self._format_troubleshooting(component_data)}

### Updates and Migrations
{self._format_migrations(component_data)}

### Backup and Recovery
{self._format_backup_recovery(component_data)}

---
*Generated by CloudMind Documentation Service*
"""
        
        return doc
    
    def _format_architecture_section(self, data: Dict[str, Any]) -> str:
        """Format architecture section"""
        if 'architecture' not in data:
            return "Architecture details not available."
        
        arch = data['architecture']
        return f"""
### Design Pattern
- **Pattern**: {arch.get('pattern', 'N/A')}
- **Type**: {arch.get('type', 'N/A')}

### Components
{self._format_list(arch.get('components', []))}

### Data Flow
{self._format_data_flow(arch.get('data_flow', []))}
"""
    
    def _format_api_endpoints(self, data: Dict[str, Any]) -> str:
        """Format API endpoints section"""
        if 'endpoints' not in data:
            return "API endpoints not available."
        
        endpoints = data['endpoints']
        formatted = ""
        
        for endpoint in endpoints:
            formatted += f"""
#### {endpoint.get('method', 'GET')} {endpoint.get('path', '/')}
- **Description**: {endpoint.get('description', 'N/A')}
- **Authentication**: {endpoint.get('auth', 'Required')}
- **Parameters**: {self._format_parameters(endpoint.get('parameters', []))}
- **Response**: {endpoint.get('response', 'N/A')}
"""
        
        return formatted
    
    def _format_database_schema(self, data: Dict[str, Any]) -> str:
        """Format database schema section"""
        if 'database' not in data:
            return "Database schema not available."
        
        db = data['database']
        return f"""
### Tables
{self._format_tables(db.get('tables', []))}

### Relationships
{self._format_relationships(db.get('relationships', []))}

### Indexes
{self._format_indexes(db.get('indexes', []))}
"""
    
    def _format_security_section(self, data: Dict[str, Any]) -> str:
        """Format security section"""
        if 'security' not in data:
            return "Security details not available."
        
        security = data['security']
        return f"""
### Authentication
{self._format_list(security.get('authentication', []))}

### Authorization
{self._format_list(security.get('authorization', []))}

### Data Protection
{self._format_list(security.get('data_protection', []))}

### Compliance
{self._format_list(security.get('compliance', []))}
"""
    
    def _format_configuration_section(self, data: Dict[str, Any]) -> str:
        """Format configuration section"""
        if 'configuration' not in data:
            return "Configuration details not available."
        
        config = data['configuration']
        return f"""
### Environment Variables
{self._format_env_vars(config.get('environment_variables', []))}

### Settings
{self._format_settings(config.get('settings', {}))}
"""
    
    def _format_usage_examples(self, data: Dict[str, Any]) -> str:
        """Format usage examples"""
        if 'examples' not in data:
            return "Usage examples not available."
        
        examples = data['examples']
        formatted = ""
        
        for i, example in enumerate(examples, 1):
            formatted += f"""
#### Example {i}: {example.get('title', 'Usage Example')}
```{example.get('language', 'python')}
{example.get('code', '# Code example')}
```
**Description**: {example.get('description', 'N/A')}
"""
        
        return formatted
    
    def _format_error_handling(self, data: Dict[str, Any]) -> str:
        """Format error handling section"""
        if 'error_handling' not in data:
            return "Error handling details not available."
        
        errors = data['error_handling']
        formatted = ""
        
        for error in errors:
            formatted += f"""
#### {error.get('code', 'N/A')} - {error.get('name', 'Error')}
- **Description**: {error.get('description', 'N/A')}
- **Cause**: {error.get('cause', 'N/A')}
- **Solution**: {error.get('solution', 'N/A')}
"""
        
        return formatted
    
    def _format_performance_section(self, data: Dict[str, Any]) -> str:
        """Format performance section"""
        if 'performance' not in data:
            return "Performance details not available."
        
        perf = data['performance']
        return f"""
### Metrics
{self._format_list(perf.get('metrics', []))}

### Optimization
{self._format_list(perf.get('optimization', []))}

### Benchmarks
{self._format_list(perf.get('benchmarks', []))}
"""
    
    def _format_testing_section(self, data: Dict[str, Any]) -> str:
        """Format testing section"""
        if 'testing' not in data:
            return "Testing details not available."
        
        testing = data['testing']
        return f"""
### Unit Tests
{self._format_list(testing.get('unit_tests', []))}

### Integration Tests
{self._format_list(testing.get('integration_tests', []))}

### Performance Tests
{self._format_list(testing.get('performance_tests', []))}
"""
    
    def _format_deployment_section(self, data: Dict[str, Any]) -> str:
        """Format deployment section"""
        if 'deployment' not in data:
            return "Deployment details not available."
        
        deploy = data['deployment']
        return f"""
### Requirements
{self._format_list(deploy.get('requirements', []))}

### Steps
{self._format_list(deploy.get('steps', []))}

### Environment
{self._format_list(deploy.get('environment', []))}
"""
    
    def _format_dependencies(self, data: Dict[str, Any]) -> str:
        """Format dependencies"""
        if 'dependencies' not in data:
            return "Dependencies not available."
        
        deps = data['dependencies']
        return f"""
### Required Dependencies
{self._format_list(deps.get('required', []))}

### Optional Dependencies
{self._format_list(deps.get('optional', []))}

### Development Dependencies
{self._format_list(deps.get('dev', []))}
"""
    
    def _format_environment_variables(self, data: Dict[str, Any]) -> str:
        """Format environment variables"""
        if 'env_vars' not in data:
            return "Environment variables not available."
        
        env_vars = data['env_vars']
        formatted = ""
        
        for var in env_vars:
            formatted += f"""
#### {var.get('name', 'VARIABLE_NAME')}
- **Description**: {var.get('description', 'N/A')}
- **Type**: {var.get('type', 'string')}
- **Required**: {var.get('required', False)}
- **Default**: {var.get('default', 'N/A')}
"""
        
        return formatted
    
    def _format_logging_section(self, data: Dict[str, Any]) -> str:
        """Format logging section"""
        if 'logging' not in data:
            return "Logging details not available."
        
        logging_config = data['logging']
        return f"""
### Log Levels
{self._format_list(logging_config.get('levels', []))}

### Log Format
{logging_config.get('format', 'N/A')}

### Log Locations
{self._format_list(logging_config.get('locations', []))}
"""
    
    def _format_monitoring_section(self, data: Dict[str, Any]) -> str:
        """Format monitoring section"""
        if 'monitoring' not in data:
            return "Monitoring details not available."
        
        monitoring = data['monitoring']
        return f"""
### Metrics
{self._format_list(monitoring.get('metrics', []))}

### Alerts
{self._format_list(monitoring.get('alerts', []))}

### Dashboards
{self._format_list(monitoring.get('dashboards', []))}
"""
    
    def _format_troubleshooting(self, data: Dict[str, Any]) -> str:
        """Format troubleshooting section"""
        if 'troubleshooting' not in data:
            return "Troubleshooting details not available."
        
        troubleshooting = data['troubleshooting']
        formatted = ""
        
        for issue in troubleshooting:
            formatted += f"""
#### {issue.get('title', 'Issue')}
- **Symptoms**: {issue.get('symptoms', 'N/A')}
- **Cause**: {issue.get('cause', 'N/A')}
- **Solution**: {issue.get('solution', 'N/A')}
- **Prevention**: {issue.get('prevention', 'N/A')}
"""
        
        return formatted
    
    def _format_migrations(self, data: Dict[str, Any]) -> str:
        """Format migrations section"""
        if 'migrations' not in data:
            return "Migration details not available."
        
        migrations = data['migrations']
        return f"""
### Database Migrations
{self._format_list(migrations.get('database', []))}

### Code Migrations
{self._format_list(migrations.get('code', []))}

### Configuration Migrations
{self._format_list(migrations.get('configuration', []))}
"""
    
    def _format_backup_recovery(self, data: Dict[str, Any]) -> str:
        """Format backup and recovery section"""
        if 'backup_recovery' not in data:
            return "Backup and recovery details not available."
        
        backup = data['backup_recovery']
        return f"""
### Backup Strategy
{self._format_list(backup.get('strategy', []))}

### Recovery Procedures
{self._format_list(backup.get('recovery', []))}

### Testing
{self._format_list(backup.get('testing', []))}
"""
    
    def _format_list(self, items: List[str]) -> str:
        """Format a list of items"""
        if not items:
            return "None specified."
        
        formatted = ""
        for item in items:
            formatted += f"- {item}\n"
        return formatted
    
    def _format_parameters(self, params: List[Dict[str, Any]]) -> str:
        """Format API parameters"""
        if not params:
            return "No parameters"
        
        formatted = ""
        for param in params:
            formatted += f"- {param.get('name', 'N/A')}: {param.get('type', 'N/A')} - {param.get('description', 'N/A')}\n"
        return formatted
    
    def _format_tables(self, tables: List[Dict[str, Any]]) -> str:
        """Format database tables"""
        if not tables:
            return "No tables specified"
        
        formatted = ""
        for table in tables:
            formatted += f"""
#### {table.get('name', 'Table')}
- **Description**: {table.get('description', 'N/A')}
- **Columns**: {self._format_columns(table.get('columns', []))}
"""
        return formatted
    
    def _format_columns(self, columns: List[Dict[str, Any]]) -> str:
        """Format table columns"""
        if not columns:
            return "No columns"
        
        formatted = ""
        for col in columns:
            formatted += f"- {col.get('name', 'N/A')}: {col.get('type', 'N/A')} - {col.get('description', 'N/A')}\n"
        return formatted
    
    def _format_relationships(self, relationships: List[Dict[str, Any]]) -> str:
        """Format database relationships"""
        if not relationships:
            return "No relationships"
        
        formatted = ""
        for rel in relationships:
            formatted += f"- {rel.get('from', 'N/A')} -> {rel.get('to', 'N/A')}: {rel.get('type', 'N/A')}\n"
        return formatted
    
    def _format_indexes(self, indexes: List[Dict[str, Any]]) -> str:
        """Format database indexes"""
        if not indexes:
            return "No indexes"
        
        formatted = ""
        for idx in indexes:
            formatted += f"- {idx.get('name', 'N/A')}: {idx.get('columns', 'N/A')} ({idx.get('type', 'N/A')})\n"
        return formatted
    
    def _format_data_flow(self, flow: List[Dict[str, Any]]) -> str:
        """Format data flow"""
        if not flow:
            return "No data flow specified"
        
        formatted = ""
        for step in flow:
            formatted += f"- {step.get('from', 'N/A')} -> {step.get('to', 'N/A')}: {step.get('description', 'N/A')}\n"
        return formatted
    
    def _format_env_vars(self, env_vars: List[Dict[str, Any]]) -> str:
        """Format environment variables"""
        if not env_vars:
            return "No environment variables"
        
        formatted = ""
        for var in env_vars:
            formatted += f"- {var.get('name', 'N/A')}: {var.get('description', 'N/A')}\n"
        return formatted
    
    def _format_settings(self, settings: Dict[str, Any]) -> str:
        """Format settings"""
        if not settings:
            return "No settings"
        
        formatted = ""
        for key, value in settings.items():
            formatted += f"- {key}: {value}\n"
        return formatted
    
    async def _generate_json_doc(self, component_name: str, component_data: Dict[str, Any]) -> str:
        """Generate JSON documentation"""
        doc_data = {
            "component_name": component_name,
            "generated_at": datetime.now().isoformat(),
            "data": component_data
        }
        return json.dumps(doc_data, indent=2)
    
    async def _generate_yaml_doc(self, component_name: str, component_data: Dict[str, Any]) -> str:
        """Generate YAML documentation"""
        doc_data = {
            "component_name": component_name,
            "generated_at": datetime.now().isoformat(),
            "data": component_data
        }
        return yaml.dump(doc_data, default_flow_style=False)
    
    async def save_documentation(self, component_name: str, content: str, doc_type: str = "md") -> str:
        """Save documentation to file"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{component_name}_{timestamp}.{doc_type}"
        filepath = self.docs_path / filename
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        logger.info(f"Documentation saved to {filepath}")
        return str(filepath) 